config/routes.rb
Rails.application.routes.draw do



  # get  '/admins/tetrisadsignin00231', to: 'admin/sessions#new'
  # post '/admins/sign_in', to: 'devise/sessions#create'
  # delete '/admins/sign_out', to: 'devise/sessions#destroy'
  # post  '/admins/password', to:  'devise/passwords#create'
  # get   '/admins/password/new', to: 'devise/passwords#new'
  # get    '/admins/password/edit', to: 'devise/passwords#edit'
  # patch '/admins/password',      to:'devise/passwords#update'
  # put   '/admins/password', to: 'devise/passwords#update'
  # get   '/admins/cancel', to:    'devise/registrations#cancel'
  # post   '/admins', to: 'devise/registrations#create'
  # # get  '/admins/sign_up', to: 'devise/registrations#new', as:'tetrisadsignin00232'
  # get  '/admins/edit', to: 'devise/registrations#edit'
  # patch  '/admins', to: 'devise/registrations#update'
  # put '/admins', to: 'devise/registrations#update'
  # delete '/admins', to: 'devise/registrations#destroy'
  #
  #
  #
  #





  resource :cart, only: [ :create]
  resources :order_items, only: [:show,:create, :update, :destroy]
  resources :order_items, only: [:create]
  devise_for :users, controllers: {:sessions => 'sessions/sessions'}
  devise_for :admins

  root 'static_pages#index'

  get '/store', to: 'products#index'
  get '/product/new', to: 'products#new'
  get '/product/:id', to: 'products#show', as: 'product'
  post '/product', to: 'products#create'
  get '/product/:id/edit', to: 'products#edit', as:'product_edit'
  patch '/product/:id', to: 'products#update'
  put '/product/:id', to: 'products#update'
  delete '/product/:id', to: 'products#destroy'

  get '/about', to: 'static_pages#about'

  get '/customercare', to: 'static_pages#customer_care'

  get '/account', to: 'static_pages#account'

  get '/dashboard', to: 'orders#show'

  get 'orders/new', to: 'orders#new'

  get 'orders/destroy', to: 'orders#destroy'

  patch '/delivered', to: 'orders#delivered'

  get '/cart', to: 'carts#show'

  get '/cart', to: 'carts#create'

  patch '/order_item/:id', to: 'cart#update'

  delete '/order_item/:id', to: 'cart#destroy'

  patch '/order_items', to: 'order_items#create'

  get '/checkout', to: 'orders#checkout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

before_filter :authenticate_user!

  layout 'header'

    def create
      @order_items = current_order.order_items.new(order_item_params)
      @order_items.save
    end

    def show
      @order = current_order
      @order_items = current_order.order_items
    end

  def update
    @order_items = current_order.order_items.find(params[:id])
    @order_items.update_attributes(order_item_params)
  end


  def destroy
    @order_items = current_order.order_items
    @order_items = current_order.order_items.find(params[:id])
    @order_items.destroy
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_row.html.erb
<div id="order_item_holder">
      <%= link_to (image_tag product.image.thumb.url, id: "cart_image"), product%>
      <h4><%= product.name %></h4>

      <%= form_for order_item, remote: true do |f| %>
        <h4 id="order_item_price"><%= number_to_currency order_item.unit_price %></h4>
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1, id: "quantity_cart" %>
            <%= f.hidden_field :product_id, value: product.id %>
              <%= f.submit "Update Quantity", id:"update_quantity"%>
              <%= link_to image_tag("closeicon", alt:"removefromcart", id: "remove_from_cart"), order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true } %>
      <% end %>

      <hr>
</div>

app/views/carts/_checkout_aside.html.erb
<div id="order_total">
  Total: <%= number_to_currency(current_order.subtotal, unit: "N")%>
</div>

app/views/carts/_search_bar.html.erb
<div id="search_bar" class="nav cf">
  <%=form_tag store_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search],placeholder: "Shorts,t-shirts,shoes. . ." %>
    </p>
    <p><%=link_to(image_tag("search",alt:"Search", id: "search_icon"), store_path,:method => 'get')%></p>
  <% end %>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div>
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if @order_items.size == 0 %>
  <div id="empty_cart_text">
      There are no items in your shopping cart.  Please go to the <%= link_to "store", store_path %> and pick up a few.
  </div>
<% else %>

    <div class="shopping_cart">
      <% @order_items.each do |order_item| %>
          <%= render 'carts/cart_row', product: order_item.product, order_item: order_item %>
      <% end %>

       <% if current_order.subtotal > 0%>
          <div id="order_subtotal">
            <h4>Sub-total <%= number_to_currency(current_order.subtotal, unit: "N") %></h4>
          </div>
       <%end%>
    </div>
<%end%>

<%if current_order.subtotal > 0%>
  <div id="checkout_aside">
         <%=render 'carts/checkout_aside'%>
    <div id="checkout_button">
      <%= link_to "Checkout", checkout_path%>
    </div>
  </div>
<%end%>

app/views/carts/show.html.erb
<div id="shopping_cart_holder" class="shopping-cart">
    <%= render "shopping_cart" %>
</div>