config/routes.rb
Rails.application.routes.draw do



  # get  '/admins/tetrisadsignin00231', to: 'admin/sessions#new'
  # post '/admins/sign_in', to: 'devise/sessions#create'
  # delete '/admins/sign_out', to: 'devise/sessions#destroy'
  # post  '/admins/password', to:  'devise/passwords#create'
  # get   '/admins/password/new', to: 'devise/passwords#new'
  # get    '/admins/password/edit', to: 'devise/passwords#edit'
  # patch '/admins/password',      to:'devise/passwords#update'
  # put   '/admins/password', to: 'devise/passwords#update'
  # get   '/admins/cancel', to:    'devise/registrations#cancel'
  # post   '/admins', to: 'devise/registrations#create'
  # # get  '/admins/sign_up', to: 'devise/registrations#new', as:'tetrisadsignin00232'
  # get  '/admins/edit', to: 'devise/registrations#edit'
  # patch  '/admins', to: 'devise/registrations#update'
  # put '/admins', to: 'devise/registrations#update'
  # delete '/admins', to: 'devise/registrations#destroy'
  #
  #
  #
  #





  resource :cart, only: [ :create]
  resources :order_items, only: [:show,:create, :update, :destroy]
  resources :order_items, only: [:create]
  devise_for :users, controllers: {:sessions => 'sessions/sessions'}
  devise_for :admins

  root 'static_pages#index'

  get '/store', to: 'products#index'
  get '/product/new', to: 'products#new'
  get '/product/:id', to: 'products#show', as: 'product'
  post '/product', to: 'products#create'
  get '/product/:id/edit', to: 'products#edit', as:'product_edit'
  patch '/product/:id', to: 'products#update'
  put '/product/:id', to: 'products#update'
  delete '/product/:id', to: 'products#destroy'

  get '/about', to: 'static_pages#about'

  get '/customercare', to: 'static_pages#customer_care'

  get '/account', to: 'static_pages#account'

  get '/dashboard', to: 'orders#show'

  get 'orders/new', to: 'orders#new'

  get 'orders/destroy', to: 'orders#destroy'

  patch '/delivered', to: 'orders#delivered'

  get '/cart', to: 'carts#show'

  get '/cart', to: 'carts#create'

  patch '/order_item/:id', to: 'cart#update'

  delete '/order_item/:id', to: 'cart#destroy'

  patch '/order_items', to: 'order_items#create'

  get '/checkout', to: 'orders#checkout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :order_items

  enum status: [:active, :featured]

  validates :name, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :image, presence: true

  def self.search(search)
  if search
    where(['name LIKE ?', "%#{search}%"])
  else
    all
  end
end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin!, only: [:create, :new, :edit, :update, :destroy]

  layout 'header'

  def index
    @products = Product.all.search(params[:search]).paginate(page: params[:page], per_page: 8)
    @search = params[:search]
    @order_item = current_order.order_items.new
  end

  def new
    @product = Product.new
  end


  def show
    @product = Product.find(params[:id])
    @order_item = OrderItem.new
    @order_item.save
  end


  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update!(product_params)
    redirect_to @product
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to 'index'
    else
      render 'show'
    end

  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :active, :status,:product_id, :image)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<div class="product">
      <% if user_signed_in?%>

      <%=link_to(product) do%>
      <div class="card">
        <div class="front_signed_in" style='background-image: url(<%= product.image.store.url%>)'>
          <%= render 'product_front', product: product%>
       </div>
       <%end%>
     </div>
          <p id="store_product_name"><%=product.name.capitalize%></p>
        <%else%>
          <div class="card">
            <div class="front" style='background-image: url(<%= product.image.store.url%>)'>
              <%= render 'product_front', product: product%>
           </div>
            <div class="back">
              <%= render 'product_back', product: product%>
            </div>
          </div>
          <p id="store_product_name"><%=product.name.capitalize%><p>
      <%end%>
</div>

app/views/products/_product_back.html.erb
<div class="links">
      <%= link_to "View Product", product%>
      <%= link_to "Sign in to add to cart", new_user_session_path%>
</div>

app/views/products/_search_bar.html.erb
<div id="search_bar" class="nav cf">
  <%=form_tag store_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search],placeholder: "Shorts,t-shirts,shoes. . ." %>
    </p>
    <p><%=link_to(image_tag("search",alt:"Search", id: "search_icon"), store_path,:method => 'get')%></p>
  <% end %>
</div>

app/views/products/create.html.erb
<h1>Product#create</h1>
<p>Find me in app/views/product/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Product#destroy</h1>
<p>Find me in app/views/product/destroy.html.erb</p>

app/views/products/edit.html.erb
<div id="edit_product_form">
  <%= form_for @product, html: {multipart: true} do |f|  %>
      <% if @product.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@product.errors.count, "error") %> prohibited this pet from being saved:</h2>

       <ul>
       <% @product.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
       </ul>
     </div>
    <% end %>

    <ul>
      <% if f.object.image? %>
      <%= image_tag f.object.image.thumb.url, style: "width:200px; height:200px;" %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %>
    <% end %>
      <li><%= f.file_field :image, placeholder: "Image" %></li>
      <li><%= f.text_field :name, placeholder: "Name" %></li>
      <li><%= f.number_field :price, placeholder: "Price"%></li>
      <li><%= f.check_box :active%></li>
      <li><%= f.check_box :featured%></li>
      <li><%= f.submit "Done" %></li>
    </ul>
  <%end%>
</div>

app/views/products/index.html.erb
<div id="product_holder">

<% provide(:title, "Store")%>


<div>
  <% if @products.blank?%>
  <div class="empty_page">
      <h1>Oh wow! nothing matches <%= @search %>, try searching for something else or go to <%=link_to("the store", store_path)%> and see what we got</h1>
  </div>
    <div class="product_holder">
  <%else%>

    <% @products.each do |product| %>
      <%= render "product", product: product, order_item: @order_item %>
    <% end %>
    <%= will_paginate @products %>
  <%end%>
    </div>

</div>

</div>

app/views/products/new.html.erb
<div id="new_product_form">
  <%= form_for @product, html: {multipart: true}, url: {action: "create"} do |f|  %>
      <% if @product.errors.any? %>
       <div id="error_explanation">
           <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
             <ul>
               <% @product.errors.full_messages.each do |message| %>
                 <li><%= message %></li>
               <% end %>
             </ul>
       </div>
    <% end %>

    <ul>
      <% if f.object.image? %>
        <%= image_tag f.object.image.thumb.url %>
        <%= f.label :remove_image %>
        <%= f.check_box :remove_image %>
      <% end %>
      <li><%= f.file_field :image, placeholder: "Image" %></li>

      <li><%= f.text_field :name, placeholder: "Name" %></li>
      <li><%= f.number_field :price, placeholder: "Price"%></li>


      <li>
        <%= f.label :active%>

        <%= f.select :status, Product.statuses.keys.map { |w| [w.humanize, w]}%>
      </li>

      <li><%= f.submit "Done" %></li>
    </ul>
  <%end%>
</div>

app/views/products/show.html.erb
  <div class="product_show">
      <%= image_tag @product.image.thumb.url, id: "product_image"%>
      <h2><%= @product.name.upcase %></h2>
      <h4 class="text-right">Price:<%= number_to_currency( @product.price, unit: "N") %></h4>
      <% if admin_signed_in?%>
        <%= link_to 'Edit', product_edit_path(@product) %> |
        <%= link_to 'Back', product_path %>
      <%end%>

      <div id = "show_controls">
        <%= form_for @order_item, remote: true do |f| %>
            <%= f.number_field :quantity, value:1, min: 1%>
            <%= f.hidden_field :price, value: @product.price %>
            <%= f.hidden_field :product_id, value:   @product.id %>
            <%= f.submit "Add to Cart"%>
        <%end%>
      </div>
</div>

app/views/products/update.html.erb
<h1>Product#update</h1>
<p>Find me in app/views/product/update.html.erb</p>