config/routes.rb
Rails.application.routes.draw do



  # get  '/admins/tetrisadsignin00231', to: 'admin/sessions#new'
  # post '/admins/sign_in', to: 'devise/sessions#create'
  # delete '/admins/sign_out', to: 'devise/sessions#destroy'
  # post  '/admins/password', to:  'devise/passwords#create'
  # get   '/admins/password/new', to: 'devise/passwords#new'
  # get    '/admins/password/edit', to: 'devise/passwords#edit'
  # patch '/admins/password',      to:'devise/passwords#update'
  # put   '/admins/password', to: 'devise/passwords#update'
  # get   '/admins/cancel', to:    'devise/registrations#cancel'
  # post   '/admins', to: 'devise/registrations#create'
  # # get  '/admins/sign_up', to: 'devise/registrations#new', as:'tetrisadsignin00232'
  # get  '/admins/edit', to: 'devise/registrations#edit'
  # patch  '/admins', to: 'devise/registrations#update'
  # put '/admins', to: 'devise/registrations#update'
  # delete '/admins', to: 'devise/registrations#destroy'
  #
  #
  #
  #





  resource :cart, only: [ :create]
  resources :order_items, only: [:show,:create, :update, :destroy]
  resources :order_items, only: [:create]
  devise_for :users, controllers: {:sessions => 'sessions/sessions'}
  devise_for :admins

  root 'static_pages#index'

  get '/store', to: 'products#index'
  get '/product/new', to: 'products#new'
  get '/product/:id', to: 'products#show', as: 'product'
  post '/product', to: 'products#create'
  get '/product/:id/edit', to: 'products#edit', as:'product_edit'
  patch '/product/:id', to: 'products#update'
  put '/product/:id', to: 'products#update'
  delete '/product/:id', to: 'products#destroy'

  get '/about', to: 'static_pages#about'

  get '/customercare', to: 'static_pages#customer_care'

  get '/account', to: 'static_pages#account'

  get '/dashboard', to: 'orders#show'

  get 'orders/new', to: 'orders#new'

  get 'orders/destroy', to: 'orders#destroy'

  patch '/delivered', to: 'orders#delivered'

  get '/cart', to: 'carts#show'

  get '/cart', to: 'carts#create'

  patch '/order_item/:id', to: 'cart#update'

  delete '/order_item/:id', to: 'cart#destroy'

  patch '/order_items', to: 'order_items#create'

  get '/checkout', to: 'orders#checkout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_cart_text.html.erb
<%= link_to "Cart( #{number_to_currency(current_order.subtotal,unit: "N")} )", cart_path, class: "cart-text" %>

app/views/layouts/_footer.html.erb
<footer class="cf">



  <div id="footer_links">
    <ul>
      <li><%= link_to( 'Store',  store_path)%></li>
      <li><%= link_to( 'about us', about_path)%></li>
      <li><%= link_to( 'need help?', customercare_path)%></li>
    </ul>
  </div>

  <div id="social_media">
    <%= link_to( image_tag("instagram.svg", alt: 'instagram'), '#')%>
  </div>

  <div id="naude">
    <p>designed by naude</p>
  </div>


</footer>

app/views/layouts/_header.html.erb
<header>
  <div id="header" class="cf">
    <%= link_to image_tag('logo', alt:"tetris", id: "header_logo"), root_path %>
    <div class="nav cf">
      <ul>
        <% if user_signed_in?%>
          <li class="drop_down">
            <%=current_user.first_name[0..3] + "." +current_user.last_name[0].upcase%>

            <ul class="sub-menu">
              <li><%=link_to "Account", account_path%></li>
              <li><%= render 'layouts/cart_text'%></li>
              <li><%=link_to "Sign out", destroy_user_session_path,:method => :delete%></li>

            </ul>
          </li>
          <li><%=link_to "customer care", customercare_path%></li>
          <li><%=link_to "store", store_path%></li>
          <li><%=link_to "home", root_path%></li>
          <li>
            <%=render 'search_bar'%>
          </li>
        <%elsif admin_signed_in?%>
            <li class="drop_down">
              <%=current_admin.email%>

              <ul class="sub-menu">
                <li><%=link_to "Account", dashboard_path%></li>
                <li><%=link_to "Sign out", destroy_user_session_path,:method => :delete%></li>

              </ul>
            </li>
        <%else%>
          <li><%=link_to "sign in/sign up", new_user_session_path %></li>
          <li><%=link_to "customer care", customercare_path%></li>
          <li><%=link_to "store", store_path%></li>
          <li><%=link_to "home", root_path%></li>
          <li>
            <%=render 'search_bar'%>
          </li>
        <%end%>
      </ul>
    </div>

  </div>
</header>

app/views/layouts/application.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>

  </head>

  <body>


    <%= yield %>


  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>

  </head>

  <body>

    <%=render 'layouts/header'%>

    <%= yield %>

    <%=render 'layouts/footer'%>

  </body>
</html>

app/views/layouts/header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>

  </head>

  <body>

    <%=render 'layouts/header'%>

    <%= yield %>

    <%=render 'layouts/footer'%>

  </body>
</html>